<?php

/**
 * @file
 * This file is used for implementing hooks.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_field_access().
 */
function chroma_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  if ($field_definition->getType() == 'colour') {
    if (!in_array('administrator', $account->getRoles())) {
      return AccessResult::forbidden();
    }
  }
  return AccessResult::neutral();
}
